/*---------------------------------------------------------------------------------------------
 *  Copyright 2026 VibeIDE Team. All rights reserved.
 *  Licensed under the MIT License. See LICENSE.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

/**
 * `VibeJobPRCompletionService` — branch + PR formatter (pure helper)
 * (roadmap §"Real-impl tail / Phase 3b — `VibeJobPRCompletionService`
 * реальный SCM provider API: branch + draft PR через GitHub/GitLab API.
 * Сейчас только формат сообщений").
 *
 * Pure helpers — `vscode`-free. Caller hits the GitHub/GitLab REST API
 * with the values produced here; this module produces:
 *   - branch name (slug + run id; ASCII-only; safe for git refs)
 *   - PR title (≤ 72 chars; conventional commit prefix optional)
 *   - PR body (markdown with sections: summary, changes, test plan)
 *
 * Author note: keeping branch slugification + PR-body composition as
 * pure helpers is the only part that yields without an actual SCM
 * provider — the rest (auth, REST POST) is real-impl and waits on the
 * runtime wrapper.
 */

const BRANCH_NAME_MAX = 244; // Git ref limit minus refs/heads/ prefix and slack.
const PR_TITLE_MAX = 72;

const SLUG_REPLACE = /[^a-z0-9-]+/g;
const SLUG_TRIM = /^-+|-+$/g;
const SLUG_DEDUP = /-{2,}/g;

export interface BranchNameInput {
	readonly prefix?: string;
	readonly summary: string;
	readonly runId: string;
}

export type BranchNameResult =
	| { readonly ok: true; readonly branch: string; readonly slug: string }
	| { readonly ok: false; readonly reason: 'summary-empty' | 'run-id-malformed' };

const RUN_ID_PATTERN = /^[a-zA-Z0-9._-]{1,64}$/;

/**
 * Build a branch name from a human summary + a run id.
 *
 * Format: `<prefix>/<slug>-<runId>` (default prefix `vibe`).
 * Slugifies summary aggressively: lowercase, ASCII alnum + hyphens only.
 * Refuses empty/over-long summary and malformed run id.
 */
export function buildBranchName(input: BranchNameInput): BranchNameResult {
	if (typeof input.summary !== 'string' || input.summary.trim().length === 0) {
		return { ok: false, reason: 'summary-empty' };
	}
	if (typeof input.runId !== 'string' || !RUN_ID_PATTERN.test(input.runId)) {
		return { ok: false, reason: 'run-id-malformed' };
	}
	const prefix = (input.prefix ?? 'vibe').toLowerCase().replace(SLUG_REPLACE, '-').replace(SLUG_DEDUP, '-').replace(SLUG_TRIM, '') || 'vibe';
	const slug = slugify(input.summary).slice(0, BRANCH_NAME_MAX - prefix.length - input.runId.length - 2);
	if (slug.length === 0) return { ok: false, reason: 'summary-empty' };
	return { ok: true, branch: `${prefix}/${slug}-${input.runId}`, slug };
}

function slugify(s: string): string {
	return s
		.toLowerCase()
		.normalize('NFKD')
		.replace(/[̀-ͯ]/g, '')
		.replace(SLUG_REPLACE, '-')
		.replace(SLUG_DEDUP, '-')
		.replace(SLUG_TRIM, '');
}

// -----------------------------------------------------------------------------
// PR title (roadmap §"branch + draft PR")
// -----------------------------------------------------------------------------

export interface PrTitleInput {
	readonly summary: string;
	readonly conventionalCommitType?: 'feat' | 'fix' | 'chore' | 'refactor' | 'docs' | 'test' | 'perf' | 'build' | 'ci';
	readonly scope?: string;
}

export type PrTitleResult =
	| { readonly ok: true; readonly title: string }
	| { readonly ok: false; readonly reason: 'summary-empty' };

/**
 * Compose a PR title. `<type>(<scope>): <summary>` if conventional;
 * otherwise just `<summary>`. Truncates to 72 chars with a trailing ellipsis.
 */
export function buildPrTitle(input: PrTitleInput): PrTitleResult {
	const summary = (input.summary ?? '').trim();
	if (summary.length === 0) return { ok: false, reason: 'summary-empty' };
	let prefix = '';
	if (input.conventionalCommitType) {
		const scope = typeof input.scope === 'string' && input.scope.length > 0 ? `(${input.scope})` : '';
		prefix = `${input.conventionalCommitType}${scope}: `;
	}
	const full = prefix + summary;
	if (full.length <= PR_TITLE_MAX) return { ok: true, title: full };
	const room = PR_TITLE_MAX - prefix.length - 1;
	if (room <= 0) return { ok: true, title: full.slice(0, PR_TITLE_MAX - 1) + '…' };
	return { ok: true, title: prefix + summary.slice(0, room) + '…' };
}

// -----------------------------------------------------------------------------
// PR body markdown (roadmap §"draft PR")
// -----------------------------------------------------------------------------

export interface PrBodyInput {
	readonly summaryBullets: ReadonlyArray<string>;
	readonly changedFiles?: ReadonlyArray<string>;
	readonly testPlan?: ReadonlyArray<string>;
	readonly relatedIssues?: ReadonlyArray<string>;
	/** Append `Generated by VibeIDE agent` footer. Default true. */
	readonly includeAgentFooter?: boolean;
}

/**
 * Compose the PR description markdown. Pure: deterministic ordering, no IO.
 *
 * Sections rendered only when non-empty (drop-when-empty pattern). Lists
 * are de-duped, trimmed, and dropped when blank. Agent footer is opt-out
 * so users can suppress it by setting `includeAgentFooter: false`.
 */
export function buildPrBody(input: PrBodyInput): string {
	const lines: string[] = [];
	if (input.summaryBullets.length > 0) {
		const bullets = dedupeNonEmpty(input.summaryBullets);
		if (bullets.length > 0) {
			lines.push('## Summary');
			for (const b of bullets) lines.push(`- ${b}`);
			lines.push('');
		}
	}
	if (input.changedFiles && input.changedFiles.length > 0) {
		const files = dedupeNonEmpty(input.changedFiles);
		if (files.length > 0) {
			lines.push('## Changed files');
			const max = 50;
			for (const f of files.slice(0, max)) lines.push(`- \`${f}\``);
			if (files.length > max) lines.push(`- …and ${files.length - max} more`);
			lines.push('');
		}
	}
	if (input.testPlan && input.testPlan.length > 0) {
		const plan = dedupeNonEmpty(input.testPlan);
		if (plan.length > 0) {
			lines.push('## Test plan');
			for (const t of plan) lines.push(`- [ ] ${t}`);
			lines.push('');
		}
	}
	if (input.relatedIssues && input.relatedIssues.length > 0) {
		const refs = dedupeNonEmpty(input.relatedIssues);
		if (refs.length > 0) {
			lines.push('## Related');
			for (const r of refs) lines.push(`- ${r}`);
			lines.push('');
		}
	}
	if (input.includeAgentFooter !== false) {
		lines.push('---');
		lines.push('🤖 Generated by VibeIDE agent. Review carefully before merge.');
	}
	while (lines.length > 0 && lines[lines.length - 1] === '') lines.pop();
	return lines.join('\n');
}

function dedupeNonEmpty(items: ReadonlyArray<string>): readonly string[] {
	const seen = new Set<string>();
	const out: string[] = [];
	for (const raw of items) {
		if (typeof raw !== 'string') continue;
		const trimmed = raw.trim();
		if (trimmed.length === 0) continue;
		if (seen.has(trimmed)) continue;
		seen.add(trimmed);
		out.push(trimmed);
	}
	return out;
}
